spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        service: content-center
        #指定namespace和cluster
        namespace: 0f1188c0-c978-4c16-afc9-5d92c085b4bd
        cluster-name: SHANGHAI
    sentinel:
      transport:
        #指定sentinel控制台地址
        dashboard: localhost:8080
      filter:
        #打开/关闭掉对SpringMVC端点的保护
        enabled: true
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          output:
            producer:
              transactional: true
              group: tx-add-bonus-group
      bindings:
        output:
          #用来指定topic
          destination: stream-test-topic
        my-output:
          destination: stream-my-topic

  main:
    #因为，feignclient中有两个接口类中指定了同一个服务user-center,所以需要加上这个配置
    allow-bean-definition-overriding: true
  application:
    name: content-center
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      #抽样率
      probability: 1.0

server:
  port: 8010

##配置文件配置ribbon负载策略
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

logging:
  level:
    com.itmuch.contentcenter.feignclient.UserCenterFeignClient: debug
    com.itmuch.contentcenter.dao.content: debug
#feign:
#  client:
#    config:
#      #想要调用的微服务名称
#      user-center:
#        loggerLevel: full

feign:
  #为feign整个sentinel
  sentinel:
    enabled: true
  client:
    config:
      #全局配置(调用的所有微服务生效)
      default:
        loggerLevel: full
        requestInterceptors:
          - com.itmuch.contentcenter.feignclient.interceptor.TokenRelayRequestInterceptor
  httpclient:
    #让feign使用apache httpclient做请求，而不是默认的urlconnection
    enabled: true
    #连接池配置
    #feign的最大连接数
    max-connections: 200
    #feign单个路径的最大连接数
    max-connections-per-route: 50

management:
  endpoints:
    web:
      exposure:
        include: '*'

resttemplate:
  sentinel:
    #设置false,表示关闭@SentinelRestTemplate注解
    enabled: true

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    #小坑：必须指定group
    group: test-group

jwt:
  secret: chuan
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600
